sensors: 
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /Sim/SceneDroneSensors/robots/Drone1/sensors/lidar1/lidar
    max_range: 100.0
    frame_subsample: 1
    point_subsample: 1
